// EscalationCard.tsx — the CLIENT register (spec §3.2): the tally made literal,
// a type-appropriate hero, the attributed ledger, and the client-safe caveat —
// self-explanatory out of context, the artifact that rides in a client email.
//
// One skeleton drives every type. Hashes and CVEs are BANNER-LED (single-source
// authority, not a vote): the identity/exploitation hero leads and the cross-
// source tally is suppressed (hash carve-out, spec §3.1 / §5). Everything else
// leads with the tally-as-coverage headline + the segmented gauge, then the hero.
// All wording/banding comes from the verdict-lib doctrine.

import type { VerdictData } from '../verdict'
import { dualUseNote, dualUseTag, graywareLabel, hashHeadline, leadFact } from '../verdict'
import { Chip, MicroLabel } from '../ui'
import { cveLead, isBannerLed } from '../card/model'
import { Hero } from './heroes'
import { CardActions } from './CardActions'
import { Caveat, ContextList, IndicatorLine, SegGauge, SourceLedger, TallyHeadline } from './ui'
import type { CanvasTheme } from '../card/palette'

function queriedStamp(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  return d.toISOString().replace('T', ' ').slice(0, 16) + ' UTC'
}

export function EscalationCard({ data, theme }: { data: VerdictData; theme?: CanvasTheme }) {
  const banner = isBannerLed(data)
  const lead = banner ? null : leadFact(data.sources)
  const showStrongest = lead && data.band !== 'green' && data.band !== 'grey'
  const bannerHeadline = data.identityLed ? hashHeadline(data) : data.type === 'cve' ? cveLead(data) : ''
  const dualUse = dualUseNote(data.sources)
  const dualUseChip = dualUseTag(data.sources)

  return (
    <div className="overflow-hidden rounded-lg border border-line-bright bg-panel shadow-e2">
      <div className="h-0.5 bg-accent" />
      <div className="flex flex-col gap-3.5 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <MicroLabel tone="accent">Escalation draft</MicroLabel>
          <span className="font-mono text-micro text-faint">SOCDESK · TRIAGE</span>
          <div className="ml-auto">
            <CardActions data={data} theme={theme} />
          </div>
        </div>

        <IndicatorLine data={data} />

        <div className="flex flex-col gap-2">
          <MicroLabel tone="muted">Assessment</MicroLabel>
          {banner ? (
            <p className="font-display text-base font-bold leading-snug text-paper">{bannerHeadline}</p>
          ) : (
            <TallyHeadline data={data} />
          )}
          {!banner && <SegGauge data={data} />}
          {dualUseChip && (
            <div className="flex flex-wrap items-center gap-1.5">
              <Chip variant="suspicious">{dualUseChip}</Chip>
            </div>
          )}
          {showStrongest && lead && (
            <p className="text-xs leading-relaxed text-muted">
              <span className="font-semibold text-paper">Lead source:</span> {lead.phrasing}.
            </p>
          )}
          {data.band === 'grayware' && (
            <p className="text-xs leading-relaxed text-muted">
              <span className="font-semibold text-verdict-amber">Note:</span> {graywareLabel()}.
            </p>
          )}
          {dualUse && (
            <p className="text-xs leading-relaxed text-muted">
              <span className="font-semibold text-paper">Note:</span> {dualUse}
            </p>
          )}
        </div>

        <Hero data={data} />

        <div className="flex flex-col gap-2">
          <MicroLabel tone="muted">
            Evidence — third-party reputation, attributed, not independently verified
          </MicroLabel>
          <SourceLedger data={data} />
        </div>

        <ContextList data={data} />
        <Caveat />

        <p className="font-mono text-micro text-faint">
          Generated by SOCDesk · sources queried {queriedStamp(data.checkedAt)}
        </p>
      </div>
    </div>
  )
}
