// EscalationCard.tsx — the CLIENT register (spec §3.2): the tally made literal,
// a type-appropriate hero, and the attributed ledger — a clean, FACTUAL artifact
// the analyst pastes into an escalation and annotates in the email body. Honesty
// here is structure (every claim attributed, no synthesized verdict, honest
// empties), NOT disclaimer prose — the analyst owns the nuance in the email.
//
// One skeleton drives every type. Hashes and CVEs are BANNER-LED (single-source
// authority, not a vote): the identity/exploitation hero leads and the cross-
// source tally is suppressed (hash carve-out, spec §3.1 / §5). Everything else
// leads with the tally-as-coverage headline + the segmented gauge, then the hero.
// All wording/banding comes from the verdict-lib doctrine.

import type { VerdictData } from '../verdict'
import { dualUseTag, hashHeadline, leadFact } from '../verdict'
import { Chip, MicroLabel } from '../ui'
import { cveLead, isBannerLed } from '../card/model'
import { Hero } from './heroes'
import { CompareIp } from './CompareIp'
import { CardActions } from './CardActions'
import { ContextList, IndicatorLine, SegGauge, SourceLedger, TallyHeadline } from './ui'
import type { CanvasTheme } from '../card/palette'

function queriedStamp(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  return d.toISOString().replace('T', ' ').slice(0, 16) + ' UTC'
}

/** Hosting / VPN / datacenter flag from AbuseIPDB's usage type — the other big
 *  impossible-travel false-positive besides Tor (which the dual-use chip carries).
 *  Context, not a verdict. */
function networkChip(data: VerdictData): string | null {
  const usage =
    data.sources.find((s) => s.name === 'AbuseIPDB')?.facts?.find((f) => /usage type/i.test(f[0]))?.[1] ?? ''
  return /data ?cent(er|re)|hosting|vpn|cdn|transit|cloud/i.test(usage) ? 'hosting / datacenter' : null
}

export function EscalationCard({ data, theme }: { data: VerdictData; theme?: CanvasTheme }) {
  const banner = isBannerLed(data)
  const lead = banner ? null : leadFact(data.sources)
  const showStrongest = lead && data.band !== 'green' && data.band !== 'grey'
  const bannerHeadline = data.identityLed ? hashHeadline(data) : data.type === 'cve' ? cveLead(data) : ''
  const dualUseChip = dualUseTag(data.sources)
  const network = networkChip(data)

  return (
    <div className="overflow-hidden rounded-lg border border-line-bright bg-panel shadow-e2">
      <div className="h-0.5 bg-accent" />
      <div className="flex flex-col gap-3.5 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <MicroLabel tone="accent">Escalation draft</MicroLabel>
          <span className="font-mono text-micro text-faint">SOCDESK · TRIAGE</span>
          <div className="ml-auto">
            <CardActions data={data} theme={theme} />
          </div>
        </div>

        <IndicatorLine data={data} />

        <div className="flex flex-col gap-2">
          <MicroLabel tone="muted">Assessment</MicroLabel>
          {banner ? (
            <p className="font-display text-base font-bold leading-snug text-paper">{bannerHeadline}</p>
          ) : (
            <TallyHeadline data={data} />
          )}
          {!banner && <SegGauge data={data} />}
          {(dualUseChip || network || data.band === 'grayware') && (
            <div className="flex flex-wrap items-center gap-1.5">
              {dualUseChip && <Chip variant="suspicious">{dualUseChip}</Chip>}
              {data.band === 'grayware' && <Chip variant="grayware">grayware — not malware</Chip>}
              {network && <Chip variant="neutral">{network}</Chip>}
            </div>
          )}
          {showStrongest && lead && (
            <p className="text-xs leading-relaxed text-muted">
              <span className="font-semibold text-paper">Lead source:</span> {lead.phrasing}.
            </p>
          )}
        </div>

        <Hero data={data} />

        {(data.type === 'ipv4' || data.type === 'ipv6') && <CompareIp data={data} />}

        <div className="flex flex-col gap-2">
          <MicroLabel tone="muted">Evidence — attributed to public sources</MicroLabel>
          <SourceLedger data={data} />
        </div>

        <ContextList data={data} />

        <p className="font-mono text-micro text-faint">
          Generated by SOCDesk · sources queried {queriedStamp(data.checkedAt)}
        </p>
      </div>
    </div>
  )
}
